name: media_drm_id
description: A Flutter plugin to retrieve Android MediaDrm device ID securely.
version: 0.0.2
homepage: https://github.com/Semedii/media_drm_id


environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"


dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.media_drm_id
        pluginClass: MediaDrmIdPlugin

